#!/usr/bin/env python3
"""PreToolUse hook: blocks edits to generated files.

Blocks shader headers (*_shd.h) generated by build/cute-shaderc and
version files (cute_version.h, cute_version.cpp) generated by CMake.
cute_shader_bytecode.h is hand-written and NOT blocked.
"""
import sys
import json
import os

data = json.load(sys.stdin)
tool_input = data.get("tool_input", {})
file_path = tool_input.get("file_path", "")

if file_path:
    name = os.path.basename(file_path)
    norm = os.path.normpath(file_path).replace(os.sep, "/")

    if name.endswith("_shd.h"):
        print(
            f"Blocked: '{name}' is a generated file. "
            "Regenerate with build/cute-shaderc instead of editing manually.",
            file=sys.stderr,
        )
        sys.exit(2)

    for suffix, template in (
        ("include/cute_version.h", "include/cute_version.h.in"),
        ("src/cute_version.cpp", "src/cute_version.cpp.in"),
    ):
        if norm.endswith(suffix):
            print(
                f"Blocked: '{name}' is generated by CMake configure_file. "
                f"Edit {template} instead.",
                file=sys.stderr,
            )
            sys.exit(2)
