#!/usr/bin/env python3
"""PreToolUse hook: blocks edits to generated shader headers (*_shd.h).

Only files ending in _shd.h are generated by build/cute-shaderc.
cute_shader_bytecode.h is hand-written and NOT blocked.
"""
import sys
import json
import os

data = json.load(sys.stdin)
tool_input = data.get("tool_input", {})
file_path = tool_input.get("file_path", "")

if file_path:
    name = os.path.basename(file_path)
    if name.endswith("_shd.h"):
        print(
            f"Blocked: '{name}' is a generated file. "
            "Regenerate with build/cute-shaderc instead of editing manually.",
            file=sys.stderr,
        )
        sys.exit(2)
